repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: go-fmt
        name: Go Format
        entry: make fmt
        language: system
        types: [go]
        pass_filenames: false

      - id: go-lint
        name: Go Lint
        entry: make lint
        language: system
        types: [go]
        pass_filenames: false

      - id: go-test
        name: Go Test
        entry: make test
        language: system
        types: [go]
        pass_filenames: false
