openapi: 3.0.0
info:
  title: Play Go API
  description: A simple RESTful API built with Go
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local development server

tags:
  - name: users
    description: User management operations

paths:
  /api/v1/users:
    post:
      tags:
        - users
      summary: Register a new user
      description: Create a new user account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid input
        '500':
          description: Internal server error

  /api/v1/users/{id}:
    get:
      tags:
        - users
      summary: Get user by ID
      description: Retrieve user information by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: User ID
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
        '500':
          description: Internal server error

components:
  schemas:
    UserInput:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          description: User's username
        password:
          type: string
          description: User's password
          format: password

    User:
      type: object
      properties:
        id:
          type: integer
          description: User's unique identifier
        username:
          type: string
          description: User's username
        created_at:
          type: string
          format: date-time
          description: Account creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp
